### ISSUE TITLE
Seg Fault 11 while trying to login for the first time

### ISSUE THREAD

**Issue by NeoQuark** [BinaryBirds/feather#16]
Hi,

I'm following your tutorial to make my own blog using your CMS and when I try to login for the first time with the given id and password, I get a segmentation fault 11. I have no idea what could have caused it and the server crashes. This appears only when running the server from terminal. Could it be caused by a chmod or chown setting ?
<img width="866" alt="Capture d’écran 2020-08-17 à 22 42 12" src="https://user-images.githubusercontent.com/18397623/90503716-302b5180-e150-11ea-9253-fbdeeb287f25.png">

**Comment by tib** [comment]
Hi, unfortunately this is a well-known issue related to the BCrypt package / Vapor / Swift. Check #3 for more info.

Please use Xcode to run the server when using macOS, currently that's the best workaround I can offer.
