### ISSUE TITLE
Release build error

### ISSUE THREAD

**Issue by ApplebaumIan** [BinaryBirds/feather#19]
When I try to `swift build --configuration release` on both MacOS and Ubuntu I get this error:
```swift
/Users/ianapplebaum/Documents/github/feather/Sources/App/Extensions/Environment+FetchValue.swift:18:9: error: 'guard' body must not fall through, consider using a 'return' or 'throw' to exit the scope
        }
        ^
```
This doesn't show up when I do a normal build. Not sure what to make of this? 
There is a precondition on the line the compiler is unhappy with saying 
```swift
 precondition(false, """
                \(key) is not defined in the Environment.
                Check README.md or documentation for how to set environment variables.
                """)
```
I don't know why this would be an issue in the release configuration, but not the normal `swift build` or `vapor build`

**Comment by tib** [comment]
This is a bug, I'll change the precondition call to fatalError later on... fyi. it's now fixed on the dev branch (wip).

**Comment by tib** [comment]
This is already fixed on the dev branch.
