### ISSUE TITLE
CSRF protection for forms

### ISSUE THREAD

**Issue by mcritz** [BinaryBirds/feather#20]
As a site admin
I want CSRF tokens on /admin routes
So that actions I take on the site are initiated only by me.
Unlike today when I could click a malicious link and unknowingly do admin actions like change email, password, and other site content.

---

I’d like to add the [VaporCSRF](https://github.com/brokenhandsio/vapor-csrf) library to admin actions.

**Comment by tib** [comment]
This is a very good feedback, the issue is real and we should definitely address it in the near future. 👍

**Comment by mcritz** [comment]
🥇
