### ISSUE TITLE
Use the `.data` type for longer text fields.

### ISSUE THREAD

**Issue by oprisk** [BinaryBirds/feather#21]
Initial sql error due to field size constraints when porting to MySql (and presumably postgres), but not Sqlite.

I found that migration defines two columns, called 'content' & 'excerpts' with data type '.string', not as '.data', consequently causes an error on initial start.  The difference is due to data type '.string' limits the size to varchar(255), while '.data' is a blob or nearly un-limited size. The 'content' value is nearly 5k, exceeding the 255 size limit.  Two cases where necessary switching to from '.string' to '.data'

1. BlogMigration_v1_0_0

            db.schema(BlogPostModel.schema)
                .id()
                .field(BlogPostModel.FieldKeys.title, .string, .required)
                .field(BlogPostModel.FieldKeys.imageKey, .string, .required)
                .field(BlogPostModel.FieldKeys.**excerpt, .data,** .required) 
                .field(BlogPostModel.FieldKeys.**content, .data,** .required)
                .field(BlogPostModel.FieldKeys.categoryId, .uuid, .required)
                .field(BlogPostModel.FieldKeys.authorId, .uuid, .required)
                .foreignKey(BlogPostModel.FieldKeys.categoryId, references: BlogCategoryModel.schema, .id)
                .foreignKey(BlogPostModel.FieldKeys.authorId, references: BlogAuthorModel.schema, .id)
                .create(),

2. StaticPageMigration_v1_0_0

        db.schema(StaticPageModel.schema)
            .id()
            .field(StaticPageModel.FieldKeys.title, .string, .required)
            .field(StaticPageModel.FieldKeys.**content, .data** )
            .create()

**Comment by tib** [comment]
Thank you very much for reporting this. Could you create a PR with the necessary change please?

**Comment by oprisk** [comment]
New to GitHub, not sure how to apply the change

**Comment by tib** [comment]
All right then, no worries, I'll fix this real soon. ☺️
