### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by aksthelion** [BinaryBirds/feather#24]
Hello,
I'm new to this. I've just manage to install it in development environment. It doesn't seem to login and showing Invalid username or password.
Did I miss something during installation & configuration?

**Comment by aksthelion** [comment]
Never mind I figured out correct default password which is Feather and not FeatherCMS. You should update readme.

**Comment by tib** [comment]
I'll update the readme + add some more docs in the next beta release, sorry about this issue.
