### ISSUE TITLE
Please low requirements down to .macOS(.v10_15)

### ISSUE THREAD

**Issue by mkll** [BinaryBirds/feather#25]
Tib, thanks for the truly amazing product.
But could you subj? :)

**Comment by tib** [comment]
Thank you. 😄 

It's going to happen real soon, if you take a look at the dev branch the dep is already down to v10_15. 

I'll release the next version (beta.3) tomorrow, that'll contain the fix.

**Comment by mkll** [comment]
I am slightly overwhelmed by the speed at which you are developing your products. I can't keep up. :)

**Comment by ApplebaumIan** [comment]
Phew! I need a little bit longer with Catalina too! 😅
