### ISSUE TITLE
Is Feather CMS name available?

### ISSUE THREAD

**Issue by ElStefanos** [BinaryBirds/feather#34]
I recently created a cms project with your name. Trust me i didn't know this exist. The official name of my project is Feather CMS not Feather. Can i use that name?
I couldn't find your contact info sorry for asking it here.

**Comment by tib** [comment]
Hi, I'm using both the Feather / Feather CMS name, but the official name of this project is **Feather CMS** to avoid confusions with other projects named Feather. FYI: I also own the domain feathercms.com. 

It's totally up-to-you if you want to use the same Feather CMS name or not... 😅
