### ISSUE TITLE
Running Feather from Xcode causes error

### ISSUE THREAD

**Issue by mcritz** [BinaryBirds/feather#4]
Xcode Version 11.6 (11E708)

When running feather, any request results in the following error:

[ INFO ] GET / [request-id: 198CA90B-5B5A-458F-8C81-9EFE3F0B7480]
[ ERROR ] LeafError(file: "/Users/mcritz/Library/Developer/Xcode/DerivedData/feather-cngubcvrjcvskeejodbirpwuzeyd/SourcePackages/checkouts/leaf-kit/Sources/LeafKit/LeafSource/LeafSources.swift", function: "searchSources(t:on:s:)", line: 76, column: 69, reason: LeafKit.LeafError.Reason.noTemplateExists("Blog/Frontend/Home")) [request-id: 198CA90B-5B5A-458F-8C81-9EFE3F0B7480]

**Comment by MattHofmann** [comment]
@mcritz It seems that the "DerivedData" directory is not set. If you run the Vapor 4 project in Xcode, you need to set the Custom working directory in Xcode first. (Alternatively running from Terminal should work fine without setting the Custom working directory)

In Xcode click on the "Run" target -> Select "Edit Scheme..." -> "Run" -> "Options" tab -> Check the "Use custom working directory:" checkbox and select the root of your Vapor project.

Tibor explains it as well in his blog [Beginner's guide to Server side Swift using Vapor 4](https://theswiftdev.com/beginners-guide-to-server-side-swift-using-vapor-4/) in section "Custom working directory in Xcode".

**Comment by mcritz** [comment]
@MattHofmann Works when set. Thanks for that. I’m going to leave this ticket open as a note to add these directions to the README.
