### ISSUE TITLE
BASE_PATH resolution results in crash

### ISSUE THREAD

**Issue by macintosh-HD** [BinaryBirds/feather#7]
I installed feather as described in your blog post. In my `.env.development` file I configured the `BASE_PATH` as `~/git/feather/`. This resulted in a crash-loop of Xcode when I ran the server. I noticed that when I tried to visit the server for the first time a folder named `~` was created in the root directory of the project. That resulted in a cash of the server and the debugger followed by Xcode.

To me it looks like that the path is not resolved correctly.

**Comment by mcritz** [comment]
@macintosh-HD I hate to say this, but I couldn’t reproduce this. Which macOS version and Xcode version are you using?

**Comment by tib** [comment]
I could reproduce this, it can be easily fixed with the help of a small extension:

```swift
extension String {

    public var expandingTildeInPath: String {
        var path = NSString(string: self).expandingTildeInPath
        if self.hasSuffix("/") {
            path += "/"
        }
        return path
    }
}

```

@macintosh-HD do you want to submit a PR for this?

**Comment by macintosh-HD** [comment]
I just created pull request #14 that should fix the error.
