### ISSUE TITLE
Change localhost to 0.0.0.0 in Makefile

### ISSUE THREAD

**Issue by clsource** [BinaryBirds/feather#9]
In Makefile

```sh
env:
	echo '' > .env.development
	echo 'BASE_URL="http://localhost:8080"' >> .env.development
	echo 'BASE_PATH="$(CUR_DIR)/"' >> .env.development
```

Using localhost can have problems in certain configurations. (For example if you want to test the app in a different computer than your localhost e.g. 192.168.0.x).

More Info:

https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0

**Comment by tib** [comment]
Yes, it'll be better with 0.0.0.0 do you want to submit a PR?

**Comment by clsource** [comment]
Sure :)
